### ISSUE TITLE
Unable to get Kong metrics

### ISSUE THREAD

**Issue by NickyCarlisle** [signalfx/kong-plugin-signalfx#4]
I'm trying to get the SignalFX Kong plugin to work with Splunk Observability Cloud. It works with Kong Gateway v2.x but the exact same config in Kong Gateway v3.x does not work.

Here is my agent_config.yaml (for the Splunk OTEL collector) relating to Kong:

```
receivers
  smartagent/kong:
    type: collectd/kong
    host: 143.110.213.58
    port: 8001
    metrics:
    - metric: request_latency
      report: true
    - metric: connections_accepted
      report: true
    - metric: connections_active
      report: true
    - metric: connections_handled
      report: true
    - metric: kong_latency
      report: true
    - metric: connections_active
      report: true
    - metric: connections_reading
      report: true
    - metric: connections_waiting
      report: true
    - metric: connections_writing
      report: true
    - metric: database_reachable
      report: true

service:
 pipelines:
  metrics:
   receivers: [hostmetrics, otlp, signalfx, smartagent/signalfx-forwarder, smartagent/kong]
```

When I start my Splunk OTEL collector I am getting metrics from the server but not the Kong service, checking journalctl I see:

```
otelcol[25528]: 2023-01-30T17:08:05.855Z        error        signalfx/handler.go:189        Traceback (most recent call last):
otelcol[25528]:   File "/usr/lib/splunk-otel-collector/agent-bundle/lib/python3.8/site-packages/sfxrunner/scheduler/simple.py", line 57, in _call_on_interval
otelcol[25528]:     func()
otelcol[25528]:   File "/usr/lib/splunk-otel-collector/agent-bundle/collectd-python/kong/kong/reporter.py", line 56, in update_and_report
otelcol[25528]:     self.kong_state.update_from_sfx()
otelcol[25528]:   File "/usr/lib/splunk-otel-collector/agent-bundle/collectd-python/kong/kong/kong_state.py", line 63, in update_from_sfx
otelcol[25528]:     self.update_resource_metrics(status['signalfx'])
otelcol[25528]: KeyError: 'signalfx'
otelcol[25528]:         {"kind": "receiver", "name": "smartagent/kong", "pipeline": "metrics", "monitorID": "smartagentkong", "monitorType": "collectd/kong", "runnerPID": 25545, "createdTime": 1675098485.8552756, "logger": "root", "sourcePath": "/usr/lib/splunk-otel-collector/agent-bundle/lib/python3.8/site-packages/sfxrunner/logs.py", "lineno": 56}
```

When I try to start the Kong server v3.x in dbless mode with the SignalFX plugin enabled I get:

```
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:199: nginx: [warn] [kong] [C]:-1 [Penlight 1.13.1] the contents of module 'pl.xml' has been deprecated, please use a more specialized library instead (deprecated after 1.11.0, scheduled for removal in 2.0.0)
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:706: error loading module 'kong.plugins.signalfx.handler':
/usr/local/share/lua/5.1/kong/plugins/signalfx/handler.lua:1: module 'kong.plugins.log-serializers.basic' not found:No LuaRocks module found for kong.plugins.log-serializers.basic
        no field package.preload['kong.plugins.log-serializers.basic']
        no file './kong/plugins/log-serializers/basic.lua'
        no file './kong/plugins/log-serializers/basic/init.lua'
        no file './custom-auth'
        no file '/usr/local/openresty/site/lualib/kong/plugins/log-serializers/basic.ljbc'
        no file '/usr/local/openresty/site/lualib/kong/plugins/log-serializers/basic/init.ljbc'
        no file '/usr/local/openresty/lualib/kong/plugins/log-serializers/basic.ljbc'
        no file '/usr/local/openresty/lualib/kong/plugins/log-serializers/basic/init.ljbc'
        no file '/usr/local/openresty/site/lualib/kong/plugins/log-serializers/basic.lua'
        no file '/usr/local/openresty/site/lualib/kong/plugins/log-serializers/basic/init.lua'
        no file '/usr/local/openresty/lualib/kong/plugins/log-serializers/basic.lua'
        no file '/usr/local/openresty/lualib/kong/plugins/log-serializers/basic/init.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/kong/plugins/log-serializers/basic.lua'
        no file '/usr/local/share/lua/5.1/kong/plugins/log-serializers/basic.lua'
        no file '/usr/local/share/lua/5.1/kong/plugins/log-serializers/basic/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/log-serializers/basic.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/log-serializers/basic/init.lua'
        no file '/root/.luarocks/share/lua/5.1/kong/plugins/log-serializers/basic.lua'
        no file '/root/.luarocks/share/lua/5.1/kong/plugins/log-serializers/basic/init.lua'
        no file '/usr/local/share/lua/5.1/kong/plugins/log-serializers/basic.ljbc'
        no file '/usr/local/share/lua/5.1/kong/plugins/log-serializers/basic/init.ljbc'
        no file '/usr/local/openresty/site/lualib/kong/plugins/log-serializers/basic.so'
        no file '/usr/local/openresty/lualib/kong/plugins/log-serializers/basic.so'
        no file './kong/plugins/log-serializers/basic.so'
        no file '/usr/local/lib/lua/5.1/kong/plugins/log-serializers/basic.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/kong/plugins/log-serializers/basic.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/root/.luarocks/lib/lua/5.1/kong/plugins/log-serializers/basic.so'
        no file '/usr/local/openresty/site/lualib/kong.so'
        no file '/usr/local/openresty/lualib/kong.so'
        no file './kong.so'
        no file '/usr/local/lib/lua/5.1/kong.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/kong.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/root/.luarocks/lib/lua/5.1/kong.so'
stack traceback:
        [C]: in function 'require'
        /usr/local/share/lua/5.1/kong/plugins/signalfx/handler.lua:1: in main chunk
        [C]: at 0x7f808ee7ba00
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:697: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:206: in function 'load_plugin_handler'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:313: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:365: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:676: in function 'init'
        init_by_lua:3: in main chunk
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:706: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:206: in function 'load_plugin_handler'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:313: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:365: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:676: in function 'init'
        init_by_lua:3: in main chunk
```

I have installed the kong plugin using these instructions: 

https://docs.splunk.com/Observability/gdi/kong/kong.html
